# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('addition', models.FloatField(default=0)),
                ('subtraction', models.FloatField(default=0)),
                ('multiplication', models.FloatField(default=0)),
                ('division', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
