# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-16 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathisfun', '0003_auto_20170413_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='userName',
            field=models.CharField(max_length=20),
        ),
    ]
